### ISSUE TITLE
Buttons?

### ISSUE THREAD

**Issue by sigoreiss** [sigoreiss/first-project#1]
Currently have buttons on my site made with `<button>` elements nested inside `<a>` links. W3C Validator says it's wrong so I gotta do something about it. Not yet sure what tho..

Example:
`<a href="index.html"><button type="button">Домой</button></a>`

**Comment by matheusxreis** [comment]
I'm not sure what W3C say about, but what do you think about redirect using Javascript? Or even styling the link tag as a button.

**Comment by sigoreiss** [comment]
> I'm not sure what W3C say about, but what do you think about redirect using Javascript? Or even styling the link tag as a button.

Yeah, I ended up styling the anchors, thanks ✌
